services:
  db:
    image: postgres
    container_name: "db"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq:/var/lib/rabbitmq/mnesia
    networks:
      - rabbitmq_net
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 3
  api:
    image: cmaunderc/home-interface-api:latest
    build:
      context: .
      platforms:
        - linux/amd64
        - linux/arm64
      dockerfile: Dockerfile.prod
    container_name: "api"
    command: gunicorn home_api.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - db
  daemon:
    image: cmaunderc/home-interface-daemon:latest
    build:
      context: workers/.
      platforms:
        - linux/amd64
        - linux/arm64
    container_name: "daemon"
    network_mode: "host"
    depends_on:
      rabbitmq:
        condition: service_healthy
networks:
  rabbitmq_net:
    driver: bridge

volumes:
  postgres_data:
  rabbitmq:
    driver: local
