services:
  nginx:
    image: cmaunderc/home-interface-nginx:latest
    build:
      context: hub/nginx
      platforms:
        - linux/amd64
        - linux/arm64
      dockerfile: Dockerfile
  api:
    image: cmaunderc/home-interface-api:latest
    build:
      context: hub/.
      platforms:
        - linux/amd64
        - linux/arm64
      dockerfile: Dockerfile.prod
  daemon:
    image: cmaunderc/home-interface-daemon:latest
    build:
      context: hub/.
      dockerfile: workers/Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
