services:
  db:
    image: postgres
    container_name: "db"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq:/var/lib/rabbitmq/mnesia
    networks:
      - rabbitmq_net
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 3
    env_file:
      - ./.env.prod
  api:
    image: cmaunderc/home-interface-api:1.0
    container_name: "api"
    command: gunicorn home_api.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  daemon:
    image: cmaunderc/home-interface-daemon:1.0
    container_name: "daemon"
    env_file:
      - ./.env.prod
    network_mode: "host"
    depends_on:
      rabbitmq:
        condition: service_healthy
networks:
  rabbitmq_net:
    driver: bridge

volumes:
  postgres_data:
  rabbitmq:
    driver: local
