services:
  nginx:
    image: cmaunderc/home-interface-nginx:latest
    ports:
      - 1337:80
    depends_on:
      - api
    networks:
      - app_net
    volumes:
      - static_volume:/home/app/web/staticfiles
  db:
    image: postgres
    container_name: "db"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod
    networks:
      - db_net
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq:/var/lib/rabbitmq/mnesia
    networks:
      - rabbitmq_net
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 3
    env_file:
      - ./.env.prod
  api:
    image: cmaunderc/home-interface-api:latest
    container_name: "api"
    command: gunicorn home_api.wsgi:application --bind 0.0.0.0:8000 --workers 4 --timeout 90
    expose:
      - 8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    env_file:
      - ./.env.prod
    depends_on:
      - db
    networks:
      - db_net
      - app_net
  ui:
    image: cmaunderc/home-interface-ui:latest
    container_name: "ui"
    env_file:
      - .env.prod
    volumes:
      - ./ui/app:/app/app
      - ./ui/public:/app/public
    restart: always
    ports:
      - 3000:3000
    networks:
      - ui_net
  daemon:
    image: cmaunderc/home-interface-daemon:latest
    container_name: "daemon"
    env_file:
      - ./.env.prod
    networks:
      - rabbitmq_net
      - db_net
      - app_net
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_started
networks:
  db_net:
    driver: bridge
  rabbitmq_net:
    driver: bridge
  app_net:
    driver: bridge
  ui_net:
    external: true

volumes:
  postgres_data:
  rabbitmq:
    driver: local
  static_volume:
