services:
  db:
    image: postgres
    container_name: "db"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.local
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_net
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 3
    env_file:
      - ./.env.local
  api:
    build: .
    container_name: "api"
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.local
    depends_on:
      - db
  daemon:
    build: workers/.
    container_name: "daemon"
    env_file:
      - ./.env.local
    network_mode: "host"
    depends_on:
      rabbitmq:
        condition: service_healthy
networks:
  rabbitmq_net:
    driver: bridge

volumes:
  postgres_data:
