services:
  api:
    image: cmaunderc/home-interface-api:latest
    build:
      context: hub/.
      platforms:
        - linux/amd64
        - linux/arm64
      dockerfile: Dockerfile.prod
  daemon:
    image: cmaunderc/home-interface-daemon:latest
    build:
      context: hub/workers/.
      platforms:
        - linux/amd64
        - linux/arm64
