services:
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_net
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 3
    env_file:
      - ./.env.rabbit
  web:
    build: .
    ports:
      - 8000:8000
  daemon:
    build: workers/.
    env_file:
      - ./.env.local
    network_mode: "host"
    depends_on:
      rabbitmq:
        condition: service_healthy
networks:
  rabbitmq_net:
    driver: bridge
