# Generated by Django 5.1.3 on 2024-11-29 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_populate_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Light',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=2000, null=True)),
                ('ip_address', models.CharField(max_length=200, unique=True)),
                ('mac_address', models.CharField(max_length=200, unique=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.location')),
            ],
        ),
    ]
