# Generated by Django 5.1.4 on 2024-12-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_light_transition_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='light',
            name='auto_power_off_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='light',
            name='auto_power_on_time',
            field=models.TimeField(null=True),
        ),
    ]
